"""Добавлены preferred_source, age_verifed, is_adult

Revision ID: cc75b8b05e3c
Revises: 
Create Date: 2026-01-22 18:27:49.632306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc75b8b05e3c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manga', sa.Column('is_adult', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('preferred_source', sa.String(), nullable=True))
    op.add_column('users', sa.Column('age_verifed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'age_verifed')
    op.drop_column('users', 'preferred_source')
    op.drop_column('manga', 'is_adult')
    # ### end Alembic commands ###
