"""Добавлен status, translate_status

Revision ID: da2f6ba3adbe
Revises: cc75b8b05e3c
Create Date: 2026-01-23 15:36:47.437278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da2f6ba3adbe'
down_revision: Union[str, Sequence[str], None] = 'cc75b8b05e3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manga', sa.Column('status', sa.String(), nullable=True))
    op.add_column('manga', sa.Column('translate_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manga', 'translate_status')
    op.drop_column('manga', 'status')
    # ### end Alembic commands ###
